version: '3.8'

services:
  Strapi:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    environment:
      - NODE_ENV=production
    ports:
      - "1337:1337"
    volumes:
      - .:/opt/app
    command: ["npm", "run", "start"]
